export const REDUX_CONSTANTS = {
    UPDATE_ALERT_MESSAGE: 'UPDATE_ALERT_MESSAGE',
    CLEAR_ALERT_MESSAGE: 'CLEAR_ALERT_MESSAGE',
    START_LOADER: 'START_LOADER',
    STOP_LOADER: 'STOP_LOADER',
    DYNAMIC_CONTENT_CON_HEIGHT: 'DYNAMIC_CONTENT_CON_HEIGHT',
    UPDATE_USER_DETAILS: "UPDATE_USER_DETAILS",
    DARK_MODE: "DARK_MODE",
    LIGHT_MODE: "LIGHT_MODE",
    CREATE_EXPENSE: "CREATE_EXPENSE",
    GET_EXPENSES: "GET_EXPENSES",
    UPDATE_EXPENSE: "UPDATE_EXPENSE",
    DELETE_EXPENSE: "DELETE_EXPENSE"
};